sudo: required
services:
  - docker

matrix:
  include:
  - language: python
    python: 3.5
    install:
    - pip install -r backend/requirements.txt
    - pip install pylint
    - pip install coverage
    - pip install flake8
    - pip install pep8-naming
    before_script:
    - cd backend
    script:
    - flake8 ./
    - pylint backend
    - coverage run --source backend -m unittest discover
    - coverage report
    before_deploy:
    - pip install awscli
    - export PATH=$PATH:$HOME/.local/bin
    - chmod +x $TRAVIS_BUILD_DIR/remote_deploy.sh
    deploy:
      provider: script
      skip_cleanup: true
      script: remote_deploy.sh
      on:
        branch: master
  - language: node_js
    node_js: 7
    install:
    - cd $TRAVIS_BUILD_DIR/frontend
    - npm install
    - cd $TRAVIS_BUILD_DIR
    before_script:
    - cd $TRAVIS_BUILD_DIR/frontend
    script:
    - npm test
env:
  global:
  - secure: iQ3YkzmfwzWltBN2Ou/xwsrfhP7yTIG82gBC0YbaY8i7Azp2bx/01jAvitWwPrPEfyoBBBZJpyFZwtaY/1l2FNmVDGIsE5INMOrjlz+sE+xIjD65VMHQH07bKS90EJE5Uhbcstd2JcUheW+tiU+sHfldmRYj8u/hjwpXxzwAKBJ19LNB0usEyZ3UWcU5AORus2q1yoUi5LywPSH21keduYfPN/PIGu5mie4dXDTSkVfbzHP+mFF09kYMkA3hgo6yds6O+79SR/AJG2i4+STmXVjrdA5pRNTGQnl7oPVa0UZWRGJb5afdTt/yBU/68MTdkRoQP1L1nLDd0BQyQhRX0MJlqYKMuQO4UvMsDHaxhvxmJpzHt+vL3j2SURb/LztMO2onaznKERhlSidTEWGqLfFN52vJTgfL63b5kEWeXoEmnv5nqYcHjhY1qO9OD+1h+0MwEiW/Rr7qyTi+prw3H1AOMHvUVHDOwWb/GThPtxtPQl0jMmCKQPH/GjHgE6aazm6v4XQaq3WRW/5z4dfhJb8CmmWdfJBAVN70v+EIzvJxsr/RWWDaYPuh3cGczikJL3pbVgL3Enjnd5XvN/Ak+ergUocQZHc2Xlgwa6TVzHhEQNhFhDL+NpMogypkPbAtQqRva5ObmvSACWHJ7DDNIbKjEUpzzPeR6iSvcQWeSCU=
  - secure: U3ih19se/H/+znEjH6/r/IUcY3RIuB/AF1kLV6iGr4Xkzg1wiYWaN2Lls8T2ZUsibcE4e3heBNOjeL2slbHYuzJVjbIOf4MsQBF35iOGtSD5rJfFa15UrDW8Eg1O8lBlNHrW6lj4UHIjOSQVgE3jA17KGEl0BDNl2yZ0c/QzKh+vxN2dgUc0qxi07CwnRAjnuB+VYwJ75q4dMju8/bbZBUauM1XqQ4sXto+J2UTFIEzRH/vwr45VwCU2aeqQKs1LYgHCuwlTPH5G+90pr4yzrPFu1QPE7WvQARILDzOPTrSIOXwhOFO60/yPDfnTFKFrc7/xu6Zvlp3aIQjBQfQwl4QOfiC7IJPInYA4MQlZFxsjbtPYwqqQLWxG9EXYN8WDm7dm7M5aMxMVj5ChdBwU6SO4YbImokQyypZ77SDzz3SKzmmzn17zVzQt04YUv65cL12niTrruumXVfeyfDWOB8sYWF4qihjx8sgotMRAEBmAZAYCIKKXJptSmwIJtRS2De9c9la1AqB5RNKAt7xohyku1VmYou2qz3WF14DTu4fZctFsVWukvx19OIllw4xAqmxfMD0bZmIUDrwHNNveW0epdKz7MGz5qu75vBX6zpPWoqwLFTrFinm85yJPwId3ztVEjN7Nmv62MpcMAryOls8eKupsxL2mAtUJ9iWw8Wo=
